### ISSUE TITLE
Airline IATA Code Incorrect

### ISSUE THREAD

**Issue by chrisdobison** [vaop/core#37]
Airline IATA code changed in Admin Panel. New segment created for that airline, old IATA code showing (that of the airline brand rather than the operator)

**Comment by lorenzoaiello** [comment]
@chrisdobison , can you please confirm the steps to reproduce? The marketing IATA should be the one showing as the primary nearly everywhere.

**Comment by chrisdobison** [comment]
@lorenzoaiello Created airline - accidentally set the wrong IATA code. Subsequently changed the IATA code to the correct value and added a segment for the airline. Old IATA code showing in the flight number.
