### ISSUE TITLE
Adding routes / segments seems "clunky"

### ISSUE THREAD

**Issue by chrisdobison** [vaop/core#38]
It is rare we would use routes with multiple segments. Can we default to adding routes and then for those with multiple legs we can do the segments addition too? At the moment it feels like a bit of duplication by adding the route, then going in and filling in the segment - when most are just 1 segment per route. Unless I'm misunderstanding the intention there. Thanks :)

**Comment by lorenzoaiello** [comment]
Not misunderstanding the intention, it was intentionally done separately to allow more flexibility. I'll see what I can do to simplify the route management experience.
